test failure
java.lang.NullPointerException: Cannot invoke "io.grpc.Metadata.get(io.grpc.Metadata$Key)" because the return value of "io.grpc.StatusRuntimeException.getTrailers()" is null